/**
 * Strategy library + edge-decay + satellite allocation loaders.
 *
 * Backed by versioned JSON artifacts in `apps/web/data/`:
 *   - strategy_library.json        (measured + candidate strategies, cited)
 *   - strategy-decay-metrics.json  (deterministic rolling metrics, repo-canonical win definition)
 *   - satellite-allocations.json   (Satellite Strike Ch9 core/satellite cards + Ch9.4.3 checklist)
 *
 * All numbers are LOCAL scanner/dev samples, NOT the production Railway Postgres
 * verified record. The decay metrics are regenerated by
 * `scripts/compute-strategy-decay.py`.
 *
 * Reads are best-effort: a missing/corrupt file returns null/[] rather than
 * throwing, so the admin surface degrades gracefully.
 */

import fs from 'fs';
import path from 'path';

const DATA_DIR = path.join(process.cwd(), 'data');

export type RegimeFit = 'trend' | 'range' | 'both';
export type Aggressiveness = 'core' | 'satellite';

export interface MeasuredStrategy {
  id: string;
  display_name: string;
  tier: 'measured';
  source_citation: string;
  regime_fit: RegimeFit;
  aggressiveness: Aggressiveness;
  satellite_only: boolean;
  data_source: string;
  resolved_signals: number;
  historical_edge: string;
  rolling_30d: string;
  rolling_90d: string;
  realized_rr: string;
  slippage: string;
  decay_status: string;
  auto_demote: boolean;
  kill_date_review: string;
  measurement_caveat: string;
  date_range: [string, string];
  provenance: string;
}

export interface CandidateStrategy {
  id: string;
  display_name: string;
  tier: 'candidate';
  regime_fit: RegimeFit;
  source_citation: string;
  source_url?: string;
  claim: string;
  satellite_only: boolean;
  aggressiveness: Aggressiveness;
  historical_edge: string;
  decay_status: string;
  auto_demote: boolean;
  kill_date_review: string;
  provenance: string;
}

export interface StrategyLibrary {
  version: string;
  generated: string;
  _meta: {
    description: string;
    provenance: string;
    historical_baseline_pct: number;
    decay_rule: string;
    decay_floor_pct: number;
    win_definition: string;
    satellite_framework: string;
    compute_script: string;
    counts: { measured: number; candidate: number };
    [key: string]: unknown;
  };
  measured_strategies: MeasuredStrategy[];
  candidate_strategies: CandidateStrategy[];
}

export interface AllocationProfile {
  profile: 'Conservative' | 'Moderate' | 'Aggressive';
  core_pct: number;
  satellite_pct: number;
  max_satellite_pct: number;
  per_trade_risk_pct?: number;
  drawdown_rules: string[];
  allowed_satellite_strategies: string[];
}

export interface SatelliteAllocations {
  version: string;
  generated: string;
  _meta: {
    framework: string;
    core_strategy: string;
    satellite_strategies: string[];
    provenance: string;
  };
  profiles: AllocationProfile[];
  monthly_review_checklist: string[];
}

function readJson<T>(file: string): T | null {
  try {
    const raw = fs.readFileSync(path.join(DATA_DIR, file), 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return null;
  }
}

export function getStrategyLibrary(): StrategyLibrary | null {
  return readJson<StrategyLibrary>('strategy_library.json');
}

export function getSatelliteAllocations(): SatelliteAllocations | null {
  return readJson<SatelliteAllocations>('satellite-allocations.json');
}

/**
 * Classify a decay_status string into a display severity so the UI can color it
 * without re-parsing prose. Mirrors the rule in compute-strategy-decay.py.
 */
export type DecaySeverity = 'healthy' | 'watch' | 'decayed' | 'candidate';

export function decaySeverity(status: string): DecaySeverity {
  const s = status.toLowerCase();
  if (s.startsWith('healthy')) return 'healthy';
  if (s.startsWith('decayed')) return 'decayed';
  if (s.startsWith('candidate')) return 'candidate';
  return 'watch';
}
