import { NextResponse } from 'next/server';
import { readHistoryAsync } from '../../lib/signal-history';

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://tradeclaw.win';

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function fmtPrice(price: number): string {
  if (!price || price === 0) return 'N/A';
  return price.toFixed(price >= 100 ? 2 : 5);
}

export async function GET() {
  const history = await readHistoryAsync();
  const signals = history.slice(0, 50);

  const items = signals
    .map((signal) => {
      const title = `${signal.direction} ${signal.pair} ${signal.timeframe} — ${signal.confidence}% confidence`;
      const pubDate = new Date(signal.timestamp).toUTCString();
      const link = `${BASE_URL}/signal/${signal.id}`;
      const outcome4h = signal.outcomes['4h'];
      const outcome24h = signal.outcomes['24h'];

      const description = `<![CDATA[
<h2>${signal.direction} ${signal.pair} @ ${fmtPrice(signal.entryPrice)}</h2>
<table cellpadding="4" cellspacing="0" border="1" style="border-collapse:collapse;font-family:monospace">
  <tr><td><strong>Pair</strong></td><td>${signal.pair}</td></tr>
  <tr><td><strong>Timeframe</strong></td><td>${signal.timeframe}</td></tr>
  <tr><td><strong>Direction</strong></td><td>${signal.direction}</td></tr>
  <tr><td><strong>Confidence</strong></td><td>${signal.confidence}%</td></tr>
  <tr><td><strong>Entry Price</strong></td><td>${fmtPrice(signal.entryPrice)}</td></tr>
  ${signal.tp1 ? `<tr><td><strong>Take Profit 1</strong></td><td>${fmtPrice(signal.tp1)}</td></tr>` : ''}
  ${signal.sl ? `<tr><td><strong>Stop Loss</strong></td><td>${fmtPrice(signal.sl)}</td></tr>` : ''}
</table>
<h3>Signal Outcomes</h3>
<table cellpadding="4" cellspacing="0" border="1" style="border-collapse:collapse;font-family:monospace">
  <tr><th>Window</th><th>Result</th><th>P&amp;L %</th><th>Exit Price</th></tr>
  <tr>
    <td>4h</td>
    <td>${outcome4h ? (outcome4h.hit ? '✅ Hit TP' : '❌ Hit SL') : '⏳ Pending'}</td>
    <td>${outcome4h ? `${outcome4h.pnlPct > 0 ? '+' : ''}${outcome4h.pnlPct}%` : '—'}</td>
    <td>${outcome4h ? fmtPrice(outcome4h.price) : '—'}</td>
  </tr>
  <tr>
    <td>24h</td>
    <td>${outcome24h ? (outcome24h.hit ? '✅ Hit TP' : '❌ Hit SL') : '⏳ Pending'}</td>
    <td>${outcome24h ? `${outcome24h.pnlPct > 0 ? '+' : ''}${outcome24h.pnlPct}%` : '—'}</td>
    <td>${outcome24h ? fmtPrice(outcome24h.price) : '—'}</td>
  </tr>
</table>
<br/>
<p><a href="${link}">View full signal on TradeClaw →</a></p>
<hr/>
<p style="color:#666;font-size:12px">Generated by <a href="${BASE_URL}">TradeClaw</a> — Open-source AI trading signals. Self-hosted. Free forever.</p>
]]>`;

      return `    <item>
      <title>${escapeXml(title)}</title>
      <link>${link}</link>
      <guid isPermaLink="true">${link}</guid>
      <pubDate>${pubDate}</pubDate>
      <description>${description}</description>
      <category>${escapeXml(signal.pair)}</category>
      <category>${signal.direction}</category>
      <category>${signal.timeframe}</category>
    </item>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>TradeClaw — Live AI Trading Signals</title>
    <link>${BASE_URL}</link>
    <description>Live AI-generated trading signals for forex, crypto, and metals on a 5-minute cadence. Confidence-rated with TP/SL levels. Subscribe to get live signals in your RSS reader.</description>
    <language>en-us</language>
    <atom:link href="${BASE_URL}/feed.xml" rel="self" type="application/rss+xml" />
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <ttl>15</ttl>
    <managingEditor>signals@tradeclaw.win (TradeClaw)</managingEditor>
    <webMaster>signals@tradeclaw.win (TradeClaw)</webMaster>
    <image>
      <url>${BASE_URL}/favicon.ico</url>
      <title>TradeClaw</title>
      <link>${BASE_URL}</link>
    </image>
${items}
  </channel>
</rss>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/rss+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=900, stale-while-revalidate=1800',
    },
  });
}
