import { NextResponse } from 'next/server';
import { readHistoryAsync } from '../../lib/signal-history';

const BASE_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://tradeclaw.win';

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function fmtPrice(price: number): string {
  if (!price || price === 0) return 'N/A';
  return price.toFixed(price >= 100 ? 2 : 5);
}

function toIso(ts: number): string {
  return new Date(ts).toISOString();
}

export async function GET() {
  const history = await readHistoryAsync();
  const signals = history.slice(0, 50);
  const updated =
    signals.length > 0 ? toIso(signals[0].timestamp) : new Date().toISOString();

  const entries = signals
    .map((signal) => {
      const title = `${signal.direction} ${signal.pair} ${signal.timeframe} — ${signal.confidence}% confidence`;
      const link = `${BASE_URL}/signal/${signal.id}`;
      const outcome4h = signal.outcomes['4h'];
      const outcome24h = signal.outcomes['24h'];

      const content = `<![CDATA[
<h2>${signal.direction} ${signal.pair} @ ${fmtPrice(signal.entryPrice)}</h2>
<table cellpadding="4" cellspacing="0" border="1" style="border-collapse:collapse;font-family:monospace">
  <tr><td><strong>Pair</strong></td><td>${signal.pair}</td></tr>
  <tr><td><strong>Timeframe</strong></td><td>${signal.timeframe}</td></tr>
  <tr><td><strong>Direction</strong></td><td>${signal.direction}</td></tr>
  <tr><td><strong>Confidence</strong></td><td>${signal.confidence}%</td></tr>
  <tr><td><strong>Entry Price</strong></td><td>${fmtPrice(signal.entryPrice)}</td></tr>
  ${signal.tp1 ? `<tr><td><strong>Take Profit 1</strong></td><td>${fmtPrice(signal.tp1)}</td></tr>` : ''}
  ${signal.sl ? `<tr><td><strong>Stop Loss</strong></td><td>${fmtPrice(signal.sl)}</td></tr>` : ''}
</table>
<h3>Signal Outcomes</h3>
<table cellpadding="4" cellspacing="0" border="1" style="border-collapse:collapse;font-family:monospace">
  <tr><th>Window</th><th>Result</th><th>P&amp;L %</th><th>Exit Price</th></tr>
  <tr>
    <td>4h</td>
    <td>${outcome4h ? (outcome4h.hit ? 'Hit TP' : 'Hit SL') : 'Pending'}</td>
    <td>${outcome4h ? `${outcome4h.pnlPct > 0 ? '+' : ''}${outcome4h.pnlPct}%` : '—'}</td>
    <td>${outcome4h ? fmtPrice(outcome4h.price) : '—'}</td>
  </tr>
  <tr>
    <td>24h</td>
    <td>${outcome24h ? (outcome24h.hit ? 'Hit TP' : 'Hit SL') : 'Pending'}</td>
    <td>${outcome24h ? `${outcome24h.pnlPct > 0 ? '+' : ''}${outcome24h.pnlPct}%` : '—'}</td>
    <td>${outcome24h ? fmtPrice(outcome24h.price) : '—'}</td>
  </tr>
</table>
<br/>
<p><a href="${link}">View full signal on TradeClaw →</a></p>
<hr/>
<p style="color:#666;font-size:12px">Generated by <a href="${BASE_URL}">TradeClaw</a> — Open-source AI trading signals. Self-hosted. Free forever.</p>
]]>`;

      return `  <entry>
    <id>${link}</id>
    <title type="text">${escapeXml(title)}</title>
    <link href="${link}" rel="alternate" type="text/html" />
    <published>${toIso(signal.timestamp)}</published>
    <updated>${toIso(signal.timestamp)}</updated>
    <category term="${escapeXml(signal.pair)}" />
    <category term="${signal.direction}" />
    <category term="${signal.timeframe}" />
    <content type="html">${content}</content>
    <summary type="text">${escapeXml(`${signal.direction} ${signal.pair} at ${fmtPrice(signal.entryPrice)} | ${signal.confidence}% confidence${signal.tp1 ? ` | TP1: ${fmtPrice(signal.tp1)}` : ''}${signal.sl ? ` | SL: ${fmtPrice(signal.sl)}` : ''}`)}</summary>
  </entry>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <id>${BASE_URL}/atom.xml</id>
  <title type="text">TradeClaw — Live AI Trading Signals</title>
  <subtitle type="text">Live AI-generated trading signals for forex, crypto, and metals on a 5-minute cadence. Confidence-rated with TP/SL levels.</subtitle>
  <link href="${BASE_URL}" rel="alternate" type="text/html" />
  <link href="${BASE_URL}/atom.xml" rel="self" type="application/atom+xml" />
  <updated>${updated}</updated>
  <author>
    <name>TradeClaw</name>
    <uri>${BASE_URL}</uri>
    <email>signals@tradeclaw.win</email>
  </author>
  <icon>${BASE_URL}/favicon.ico</icon>
  <rights>MIT License — https://github.com/naimkatiman/tradeclaw/blob/main/LICENSE</rights>
${entries}
</feed>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/atom+xml; charset=utf-8',
      'Cache-Control': 'public, max-age=900, stale-while-revalidate=1800',
    },
  });
}
