import type { Metadata } from 'next';
import { CodeBlock } from '../components/code-block';
import { PageNav } from '../components/page-nav';
import { getPrevNext } from '../nav-config';

export const metadata: Metadata = {
  title: 'Trading Signals',
  description: 'How TradeClaw generates signals — indicators, confluence scoring, timeframes, and supported instruments.',
};

export default function SignalsPage() {
  const { prev, next } = getPrevNext('/docs/signals');

  return (
    <article>
      <div className="mb-10">
        <p className="text-sm text-emerald-400 font-medium mb-2">Core Features</p>
        <h1 className="text-4xl font-bold text-white tracking-tight mb-4">Trading Signals</h1>
        <p className="text-lg text-zinc-400 leading-relaxed">
          Every signal is generated by running five independent technical indicators and
          combining their outputs into a single confluence score. No black boxes —
          every formula is in <code className="text-emerald-400 text-base">apps/web/app/lib/ta-engine.ts</code>.
        </p>
      </div>

      {/* Instruments */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-4">Supported Instruments</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
          {[
            { symbol: 'XAUUSD', name: 'Gold', type: 'Metals' },
            { symbol: 'XAGUSD', name: 'Silver', type: 'Metals' },
            { symbol: 'USOIL', name: 'US Oil', type: 'Commodities' },
            { symbol: 'BTCUSD', name: 'Bitcoin', type: 'Crypto' },
            { symbol: 'ETHUSD', name: 'Ethereum', type: 'Crypto' },
            { symbol: 'EURUSD', name: 'EUR/USD', type: 'Forex' },
            { symbol: 'GBPUSD', name: 'GBP/USD', type: 'Forex' },
            { symbol: 'USDJPY', name: 'USD/JPY', type: 'Forex' },
            { symbol: 'AUDUSD', name: 'AUD/USD', type: 'Forex' },
            { symbol: 'USDCAD', name: 'USD/CAD', type: 'Forex' },
            { symbol: 'USDCHF', name: 'USD/CHF', type: 'Forex' },
            { symbol: 'GBPJPY', name: 'GBP/JPY', type: 'Forex' },
            { symbol: 'EURJPY', name: 'EUR/JPY', type: 'Forex' },
          ].map(i => (
            <div key={i.symbol} className="flex items-center justify-between p-3 rounded-xl border border-white/5 bg-white/[0.02]">
              <div>
                <p className="text-sm font-mono font-medium text-zinc-200">{i.symbol}</p>
                <p className="text-xs text-zinc-500">{i.name}</p>
              </div>
              <span className="text-[10px] text-zinc-600 font-medium uppercase tracking-wide">{i.type}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Timeframes */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-4">Timeframes</h2>
        <div className="flex flex-wrap gap-2">
          {[
            { tf: 'M5', label: '5-minute', use: 'Scalping, short-term momentum' },
            { tf: 'M15', label: '15-minute', use: 'Intraday swing entries' },
            { tf: 'H1', label: '1-hour', use: 'Main trading timeframe' },
            { tf: 'H4', label: '4-hour', use: 'Trend confirmation' },
            { tf: 'D1', label: 'Daily', use: 'Higher-timeframe bias' },
          ].map(t => (
            <div key={t.tf} className="flex-1 min-w-[140px] p-4 rounded-xl border border-white/5 bg-white/[0.02]">
              <p className="text-lg font-bold font-mono text-emerald-400">{t.tf}</p>
              <p className="text-xs font-medium text-zinc-300 mt-0.5">{t.label}</p>
              <p className="text-xs text-zinc-500 mt-1">{t.use}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Indicators */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-2">Indicators</h2>
        <p className="text-zinc-400 mb-6 leading-relaxed">
          The TA engine runs five indicators on every symbol/timeframe combination.
          Each indicator casts a directional vote (bullish, bearish, or neutral) which is
          weighted into the final confluence score.
        </p>

        {/* RSI */}
        <div className="mb-8 p-6 rounded-xl border border-white/6 bg-white/[0.02]">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <h3 className="text-lg font-semibold text-white">RSI — Relative Strength Index</h3>
              <p className="text-sm text-zinc-500 mt-0.5">Period: 14 · Method: Wilder&apos;s smoothing</p>
            </div>
            <code className="text-xs text-emerald-400 font-mono bg-emerald-500/8 border border-emerald-500/15 px-2 py-1 rounded shrink-0">Momentum</code>
          </div>
          <p className="text-sm text-zinc-400 mb-4 leading-relaxed">
            RSI measures the speed and change of price movements on a scale of 0–100.
            TradeClaw uses Wilder&apos;s original exponential smoothing formula.
          </p>
          <div className="grid grid-cols-3 gap-2 mb-4">
            {[
              { label: 'Oversold', threshold: '< 30', signal: 'Bullish', color: 'text-emerald-400' },
              { label: 'Neutral', threshold: '30–70', signal: 'Neutral', color: 'text-zinc-400' },
              { label: 'Overbought', threshold: '> 70', signal: 'Bearish', color: 'text-red-400' },
            ].map(r => (
              <div key={r.label} className="p-3 rounded-lg bg-white/[0.03] text-center">
                <p className="text-xs text-zinc-500">{r.label}</p>
                <p className="text-sm font-mono font-bold text-zinc-200 mt-1">{r.threshold}</p>
                <p className={`text-xs font-medium mt-0.5 ${r.color}`}>{r.signal}</p>
              </div>
            ))}
          </div>
          <CodeBlock
            language="typescript"
            code={`// Wilder's smoothing RSI (from ta-engine.ts)
function calcRSI(closes: number[], period = 14): RSIResult {
  let avgGain = 0, avgLoss = 0;
  for (let i = 1; i <= period; i++) {
    const diff = closes[i] - closes[i - 1];
    if (diff > 0) avgGain += diff; else avgLoss -= diff;
  }
  avgGain /= period; avgLoss /= period;

  for (let i = period + 1; i < closes.length; i++) {
    const diff = closes[i] - closes[i - 1];
    avgGain = (avgGain * (period - 1) + Math.max(diff, 0)) / period;
    avgLoss = (avgLoss * (period - 1) + Math.max(-diff, 0)) / period;
  }

  const rs = avgLoss === 0 ? 100 : avgGain / avgLoss;
  return { value: 100 - 100 / (1 + rs) };
}`}
          />
        </div>

        {/* MACD */}
        <div className="mb-8 p-6 rounded-xl border border-white/6 bg-white/[0.02]">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <h3 className="text-lg font-semibold text-white">MACD — Moving Average Convergence/Divergence</h3>
              <p className="text-sm text-zinc-500 mt-0.5">Fast: 12 · Slow: 26 · Signal: 9</p>
            </div>
            <code className="text-xs text-emerald-400 font-mono bg-emerald-500/8 border border-emerald-500/15 px-2 py-1 rounded shrink-0">Trend</code>
          </div>
          <p className="text-sm text-zinc-400 mb-4 leading-relaxed">
            MACD measures the relationship between two EMAs. A positive histogram means
            short-term momentum is stronger than long-term — bullish. Negative — bearish.
          </p>
          <div className="grid grid-cols-2 gap-2 mb-4">
            {[
              { label: 'Histogram > 0', signal: 'Bullish', color: 'text-emerald-400' },
              { label: 'Histogram < 0', signal: 'Bearish', color: 'text-red-400' },
            ].map(r => (
              <div key={r.label} className="p-3 rounded-lg bg-white/[0.03] text-center">
                <p className="text-xs text-zinc-500">{r.label}</p>
                <p className={`text-sm font-medium mt-1 ${r.color}`}>{r.signal}</p>
              </div>
            ))}
          </div>
          <div className="text-xs text-zinc-500 font-mono bg-white/[0.03] rounded-lg p-3 leading-loose">
            <p>MACD Line = EMA(12) - EMA(26)</p>
            <p>Signal Line = EMA(9) of MACD Line</p>
            <p>Histogram = MACD Line - Signal Line</p>
          </div>
        </div>

        {/* EMA */}
        <div className="mb-8 p-6 rounded-xl border border-white/6 bg-white/[0.02]">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <h3 className="text-lg font-semibold text-white">EMA — Exponential Moving Averages</h3>
              <p className="text-sm text-zinc-500 mt-0.5">Periods: 20, 50, 200</p>
            </div>
            <code className="text-xs text-emerald-400 font-mono bg-emerald-500/8 border border-emerald-500/15 px-2 py-1 rounded shrink-0">Trend</code>
          </div>
          <p className="text-sm text-zinc-400 mb-4 leading-relaxed">
            Three EMAs establish the trend bias. Price above EMA20 &gt; EMA50 &gt; EMA200 is a
            strong uptrend. A golden cross (EMA50 crossing above EMA200) is particularly
            weighted in the confluence score.
          </p>
          <div className="grid grid-cols-2 gap-2">
            {[
              { label: 'Price > EMA20 > EMA50', signal: 'Bullish', color: 'text-emerald-400' },
              { label: 'Golden Cross (50 > 200)', signal: 'Strong Bullish', color: 'text-emerald-400' },
              { label: 'Price < EMA20 < EMA50', signal: 'Bearish', color: 'text-red-400' },
              { label: 'Death Cross (50 < 200)', signal: 'Strong Bearish', color: 'text-red-400' },
            ].map(r => (
              <div key={r.label} className="p-3 rounded-lg bg-white/[0.03]">
                <p className="text-xs text-zinc-500">{r.label}</p>
                <p className={`text-xs font-medium mt-1 ${r.color}`}>{r.signal}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Bollinger Bands */}
        <div className="mb-8 p-6 rounded-xl border border-white/6 bg-white/[0.02]">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <h3 className="text-lg font-semibold text-white">Bollinger Bands</h3>
              <p className="text-sm text-zinc-500 mt-0.5">Period: 20 · Std Dev: 2</p>
            </div>
            <code className="text-xs text-emerald-400 font-mono bg-emerald-500/8 border border-emerald-500/15 px-2 py-1 rounded shrink-0">Volatility</code>
          </div>
          <p className="text-sm text-zinc-400 mb-4 leading-relaxed">
            Three bands (upper, middle SMA, lower) built from ±2 standard deviations.
            Price touching the lower band while other indicators are bullish = high-probability
            entry. Band squeeze (low bandwidth) often precedes a breakout.
          </p>
          <div className="text-xs text-zinc-500 font-mono bg-white/[0.03] rounded-lg p-3 leading-loose">
            <p>Upper Band = SMA(20) + 2 × StdDev(20)</p>
            <p>Middle Band = SMA(20)</p>
            <p>Lower Band = SMA(20) - 2 × StdDev(20)</p>
            <p>Bandwidth = (Upper - Lower) / Middle</p>
          </div>
        </div>

        {/* Stochastic */}
        <div className="mb-8 p-6 rounded-xl border border-white/6 bg-white/[0.02]">
          <div className="flex items-start justify-between gap-4 mb-3">
            <div>
              <h3 className="text-lg font-semibold text-white">Stochastic Oscillator</h3>
              <p className="text-sm text-zinc-500 mt-0.5">%K: 14 smooth 3 · %D: 3</p>
            </div>
            <code className="text-xs text-emerald-400 font-mono bg-emerald-500/8 border border-emerald-500/15 px-2 py-1 rounded shrink-0">Momentum</code>
          </div>
          <p className="text-sm text-zinc-400 mb-4 leading-relaxed">
            Compares a closing price to its high-low range over 14 periods.
            Values below 20 (oversold) with %K crossing above %D is a buy signal.
            Values above 80 (overbought) with %K crossing below %D is a sell signal.
          </p>
          <div className="grid grid-cols-3 gap-2">
            {[
              { label: 'Oversold', threshold: '< 20', signal: 'Bullish', color: 'text-emerald-400' },
              { label: 'Neutral', threshold: '20–80', signal: 'Neutral', color: 'text-zinc-400' },
              { label: 'Overbought', threshold: '> 80', signal: 'Bearish', color: 'text-red-400' },
            ].map(r => (
              <div key={r.label} className="p-3 rounded-lg bg-white/[0.03] text-center">
                <p className="text-xs text-zinc-500">{r.label}</p>
                <p className="text-sm font-mono font-bold text-zinc-200 mt-1">{r.threshold}</p>
                <p className={`text-xs font-medium mt-0.5 ${r.color}`}>{r.signal}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Confluence scoring */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-4">Confluence Scoring</h2>
        <p className="text-zinc-400 mb-5 leading-relaxed">
          Each indicator vote is weighted and summed to produce a final score from 0–100.
          The direction (BUY or SELL) is determined by whichever side has more weighted votes.
          A score of 80+ is considered high-confidence.
        </p>
        <div className="rounded-xl border border-white/6 overflow-hidden mb-5">
          <table className="w-full text-left">
            <thead>
              <tr className="border-b border-white/6 bg-white/[0.02]">
                <th className="px-4 py-2.5 text-xs font-semibold text-zinc-500 uppercase tracking-wide">Score Range</th>
                <th className="px-4 py-2.5 text-xs font-semibold text-zinc-500 uppercase tracking-wide">Label</th>
                <th className="px-4 py-2.5 text-xs font-semibold text-zinc-500 uppercase tracking-wide">Indicators Aligned</th>
              </tr>
            </thead>
            <tbody>
              {[
                { range: '80–100', label: 'High Confidence', count: '4–5 of 5', color: 'text-emerald-400' },
                { range: '65–79', label: 'Moderate Confidence', count: '3–4 of 5', color: 'text-zinc-400' },
                { range: '50–64', label: 'Low Confidence', count: '2–3 of 5', color: 'text-orange-400' },
                { range: '< 50', label: 'Filtered / Not Emitted', count: '< 2 of 5', color: 'text-red-400' },
              ].map(row => (
                <tr key={row.range} className="border-b border-white/4 last:border-0">
                  <td className={`px-4 py-3 text-sm font-mono font-bold ${row.color}`}>{row.range}</td>
                  <td className="px-4 py-3 text-sm text-zinc-300">{row.label}</td>
                  <td className="px-4 py-3 text-sm text-zinc-500">{row.count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="text-sm text-zinc-500">
          Signals below 50 confidence are filtered before being emitted. The screener and
          signal feed default to showing only signals with confidence ≥ 65.
        </p>
      </section>

      {/* Signal data structure */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-4">Signal Data Structure</h2>
        <CodeBlock
          language="typescript"
          code={`interface TradingSignal {
  id: string;            // Unique signal ID
  symbol: string;        // e.g. "XAUUSD"
  timeframe: string;     // e.g. "H1"
  direction: 'BUY' | 'SELL';
  confidence: number;    // 0–100 confluence score
  entryPrice: number;    // Current price at signal generation
  tp1: number;           // Take Profit 1 (1:1 R:R)
  tp2: number;           // Take Profit 2 (1:2 R:R)
  tp3: number;           // Take Profit 3 (1:3 R:R)
  sl: number;            // Stop Loss (ATR-based)
  indicators: {
    rsi: number;
    macd: number;        // histogram value
    ema20: number;
    ema50: number;
    ema200: number;
    bb_upper: number;
    bb_lower: number;
    stoch_k: number;
    stoch_d: number;
  };
  timestamp: string;     // ISO 8601
  status: 'active' | 'hit_tp1' | 'hit_tp2' | 'hit_tp3' | 'sl_hit' | 'expired';
}`}
          />
      </section>

      {/* Multi-timeframe */}
      <section className="mb-12">
        <h2 className="text-2xl font-semibold text-white mb-4">Multi-Timeframe Consensus</h2>
        <p className="text-zinc-400 mb-4 leading-relaxed">
          The <code className="text-emerald-400 bg-white/5 px-1.5 py-0.5 rounded text-xs">GET /api/signals/multi-tf</code> endpoint
          calculates direction consensus across M15, H1, H4, and D1. When all four timeframes
          agree on direction, the signal is marked as &quot;aligned&quot; — historically the highest
          win-rate scenario.
        </p>
        <div className="rounded-xl border border-emerald-500/10 bg-emerald-500/5 p-4 text-sm text-zinc-400">
          <strong className="text-emerald-400">Tip:</strong> Filter signals by{' '}
          <code className="text-emerald-400 bg-white/5 px-1.5 py-0.5 rounded text-xs">minConfidence=80</code> and
          only trade when MTF consensus is aligned. This is the highest-probability setup in the platform.
        </div>
      </section>

      <PageNav prev={prev} next={next} githubPath="apps/web/app/docs/signals/page.tsx" />
    </article>
  );
}
